package view;

import controller.CPrincipal;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import model.user.Investidor;

public class JPrincipal extends javax.swing.JFrame {
    private CPrincipal c;
    private boolean saldoVisivel = false;
    private boolean saqueSaldoVisivel = false;
    private boolean saqueSenhaVisivel = false;
    private boolean janelaIniciada = false;
    
    public JPrincipal(Investidor inv) {
        initComponents();
        janelaIniciada = true;
        c = new CPrincipal(this, inv);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jpFundo = new javax.swing.JPanel();
        jpAbas = new javax.swing.JTabbedPane();
        jpSaldo = new javax.swing.JPanel();
        lblTituloSaldo = new javax.swing.JLabel();
        lblBemVindo = new javax.swing.JLabel();
        jpValoresSaldo = new javax.swing.JPanel();
        jpSaldoReal = new javax.swing.JPanel();
        lblSaldoTotal = new javax.swing.JLabel();
        saldoTotalValor = new javax.swing.JLabel();
        lblSaldoReal = new javax.swing.JLabel();
        saldoRealValor = new javax.swing.JLabel();
        jpSaldoCriptos = new javax.swing.JPanel();
        lblSaldoBitcoin = new javax.swing.JLabel();
        saldoBitcoinQtd = new javax.swing.JLabel();
        saldoBitcoinValor = new javax.swing.JLabel();
        lblSaldoEtherium = new javax.swing.JLabel();
        saldoEtheriumQtd = new javax.swing.JLabel();
        saldoEtheriumValor = new javax.swing.JLabel();
        lblSaldoRipple = new javax.swing.JLabel();
        saldoRippleQtd = new javax.swing.JLabel();
        saldoRippleValor = new javax.swing.JLabel();
        jpSaldoBotoes = new javax.swing.JPanel();
        saldoBtAtualizar = new javax.swing.JButton();
        saldoBtVisualizar = new javax.swing.JToggleButton();
        lblSaldoCPF = new javax.swing.JLabel();
        jpScrollExtrato = new javax.swing.JScrollPane();
        jpExtrato = new javax.swing.JPanel();
        lblTituloExtrato = new javax.swing.JLabel();
        jpDepSaque = new javax.swing.JPanel();
        lblTituloSaque = new javax.swing.JLabel();
        lblTituloDeposito = new javax.swing.JLabel();
        jpDeposito = new javax.swing.JPanel();
        lblValorDeposito = new javax.swing.JLabel();
        lblSeparador1 = new javax.swing.JLabel();
        saqueDepValorDeposito = new javax.swing.JTextField();
        jpSaque = new javax.swing.JPanel();
        lblValorSaque = new javax.swing.JLabel();
        lblSeparador2 = new javax.swing.JLabel();
        saqueDepValorSaque = new javax.swing.JTextField();
        jpSaqueDepBotoes = new javax.swing.JPanel();
        saqueDepBtDepositar = new javax.swing.JButton();
        saqueDepBtViewSaldo = new javax.swing.JToggleButton();
        saqueDepBtSacar = new javax.swing.JButton();
        jpSaqueDepSaldoAtual = new javax.swing.JPanel();
        lblSaqueDepSaldo = new javax.swing.JLabel();
        saqueDepSaldo = new javax.swing.JLabel();
        jpSaqDepSenha = new javax.swing.JPanel();
        lblSaqueDepSenha = new javax.swing.JLabel();
        saqueDepSenha = new javax.swing.JPasswordField();
        saqueDepBtViewSenha = new javax.swing.JToggleButton();
        jpCompra = new javax.swing.JPanel();
        jpVenda = new javax.swing.JPanel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cripto Exchange - Menu");
        setSize(new java.awt.Dimension(840, 480));

        jpFundo.setBackground(new java.awt.Color(255, 255, 255));

        jpAbas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jpAbasStateChanged(evt);
            }
        });

        jpSaldo.setBackground(new java.awt.Color(255, 255, 255));
        jpSaldo.setPreferredSize(new java.awt.Dimension(840, 480));

        lblTituloSaldo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblTituloSaldo.setForeground(new java.awt.Color(0, 153, 204));
        lblTituloSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSaldo.setText("Saldo");

        lblBemVindo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblBemVindo.setForeground(new java.awt.Color(0, 102, 102));
        lblBemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBemVindo.setText("Bem Vindo(a) [Usuario]");

        jpValoresSaldo.setBackground(new java.awt.Color(255, 255, 255));

        jpSaldoReal.setBackground(java.awt.Color.white);
        jpSaldoReal.setLayout(new java.awt.GridLayout(2, 2, 50, 15));

        lblSaldoTotal.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblSaldoTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblSaldoTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldoTotal.setText("Saldo Total:");
        lblSaldoTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        jpSaldoReal.add(lblSaldoTotal);

        saldoTotalValor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        saldoTotalValor.setForeground(new java.awt.Color(0, 0, 0));
        saldoTotalValor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        saldoTotalValor.setText("R$ -,--");
        saldoTotalValor.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        jpSaldoReal.add(saldoTotalValor);

        lblSaldoReal.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblSaldoReal.setForeground(new java.awt.Color(0, 0, 0));
        lblSaldoReal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldoReal.setText("Real:");
        jpSaldoReal.add(lblSaldoReal);

        saldoRealValor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        saldoRealValor.setForeground(new java.awt.Color(0, 0, 0));
        saldoRealValor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        saldoRealValor.setText("R$ -,--");
        jpSaldoReal.add(saldoRealValor);

        jpSaldoCriptos.setBackground(new java.awt.Color(255, 255, 255));
        jpSaldoCriptos.setMaximumSize(new java.awt.Dimension(426, 195));
        jpSaldoCriptos.setLayout(new java.awt.GridLayout(3, 3));

        lblSaldoBitcoin.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblSaldoBitcoin.setForeground(new java.awt.Color(0, 0, 0));
        lblSaldoBitcoin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldoBitcoin.setText("Bitcoin:");
        lblSaldoBitcoin.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 1, 30));
        lblSaldoBitcoin.setMinimumSize(new java.awt.Dimension(30, 35));
        jpSaldoCriptos.add(lblSaldoBitcoin);

        saldoBitcoinQtd.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        saldoBitcoinQtd.setForeground(new java.awt.Color(0, 0, 0));
        saldoBitcoinQtd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldoBitcoinQtd.setText("QTD. -,--");
        saldoBitcoinQtd.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 1, 5));
        saldoBitcoinQtd.setMaximumSize(new java.awt.Dimension(300, 35));
        jpSaldoCriptos.add(saldoBitcoinQtd);

        saldoBitcoinValor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        saldoBitcoinValor.setForeground(new java.awt.Color(0, 0, 0));
        saldoBitcoinValor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        saldoBitcoinValor.setText("R$ -,--");
        saldoBitcoinValor.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 1, 30));
        saldoBitcoinValor.setMinimumSize(new java.awt.Dimension(30, 35));
        jpSaldoCriptos.add(saldoBitcoinValor);

        lblSaldoEtherium.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblSaldoEtherium.setForeground(new java.awt.Color(0, 0, 0));
        lblSaldoEtherium.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldoEtherium.setText("Etherium:");
        lblSaldoEtherium.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 30));
        lblSaldoEtherium.setMinimumSize(new java.awt.Dimension(30, 26));
        jpSaldoCriptos.add(lblSaldoEtherium);

        saldoEtheriumQtd.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        saldoEtheriumQtd.setForeground(new java.awt.Color(0, 0, 0));
        saldoEtheriumQtd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldoEtheriumQtd.setText("QTD. -,--");
        saldoEtheriumQtd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        saldoEtheriumQtd.setMaximumSize(new java.awt.Dimension(300, 21));
        jpSaldoCriptos.add(saldoEtheriumQtd);

        saldoEtheriumValor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        saldoEtheriumValor.setForeground(new java.awt.Color(0, 0, 0));
        saldoEtheriumValor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        saldoEtheriumValor.setText("R$ -,--");
        saldoEtheriumValor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 30));
        saldoEtheriumValor.setMinimumSize(new java.awt.Dimension(30, 26));
        jpSaldoCriptos.add(saldoEtheriumValor);

        lblSaldoRipple.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblSaldoRipple.setForeground(new java.awt.Color(0, 0, 0));
        lblSaldoRipple.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldoRipple.setText("Ripple:");
        lblSaldoRipple.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 40, 30));
        lblSaldoRipple.setMinimumSize(new java.awt.Dimension(30, 65));
        jpSaldoCriptos.add(lblSaldoRipple);

        saldoRippleQtd.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        saldoRippleQtd.setForeground(new java.awt.Color(0, 0, 0));
        saldoRippleQtd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldoRippleQtd.setText("QTD. -,--");
        saldoRippleQtd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 40, 5));
        saldoRippleQtd.setMaximumSize(new java.awt.Dimension(300, 60));
        jpSaldoCriptos.add(saldoRippleQtd);

        saldoRippleValor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        saldoRippleValor.setForeground(new java.awt.Color(0, 0, 0));
        saldoRippleValor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        saldoRippleValor.setText("R$ -,--");
        saldoRippleValor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 40, 30));
        saldoRippleValor.setMinimumSize(new java.awt.Dimension(30, 65));
        jpSaldoCriptos.add(saldoRippleValor);

        javax.swing.GroupLayout jpValoresSaldoLayout = new javax.swing.GroupLayout(jpValoresSaldo);
        jpValoresSaldo.setLayout(jpValoresSaldoLayout);
        jpValoresSaldoLayout.setHorizontalGroup(
            jpValoresSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpSaldoReal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpSaldoCriptos, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        jpValoresSaldoLayout.setVerticalGroup(
            jpValoresSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpValoresSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpSaldoReal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpSaldoCriptos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpSaldoBotoes.setBackground(new java.awt.Color(255, 255, 255));

        saldoBtAtualizar.setBackground(new java.awt.Color(0, 153, 204));
        saldoBtAtualizar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        saldoBtAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        saldoBtAtualizar.setText("Atualizar");
        saldoBtAtualizar.setFocusable(false);
        saldoBtAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoBtAtualizarActionPerformed(evt);
            }
        });
        jpSaldoBotoes.add(saldoBtAtualizar);

        saldoBtVisualizar.setBackground(new java.awt.Color(0, 153, 204));
        saldoBtVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        saldoBtVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/olho-25x25.png"))); // NOI18N
        saldoBtVisualizar.setFocusable(false);
        saldoBtVisualizar.setMaximumSize(new java.awt.Dimension(94, 26));
        saldoBtVisualizar.setMinimumSize(new java.awt.Dimension(94, 26));
        saldoBtVisualizar.setPreferredSize(new java.awt.Dimension(94, 26));
        saldoBtVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoBtVisualizarActionPerformed(evt);
            }
        });
        jpSaldoBotoes.add(saldoBtVisualizar);

        lblSaldoCPF.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblSaldoCPF.setForeground(new java.awt.Color(0, 102, 102));
        lblSaldoCPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldoCPF.setText("CPF: XXX.XXX.XXX-XX");

        javax.swing.GroupLayout jpSaldoLayout = new javax.swing.GroupLayout(jpSaldo);
        jpSaldo.setLayout(jpSaldoLayout);
        jpSaldoLayout.setHorizontalGroup(
            jpSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpValoresSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblBemVindo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpSaldoBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblSaldoCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpSaldoLayout.setVerticalGroup(
            jpSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpSaldoBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpValoresSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpAbas.addTab("Saldo", null, jpSaldo, "");

        jpScrollExtrato.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jpExtrato.setBackground(new java.awt.Color(255, 255, 255));
        jpExtrato.setPreferredSize(new java.awt.Dimension(840, 480));

        lblTituloExtrato.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblTituloExtrato.setForeground(new java.awt.Color(0, 153, 204));
        lblTituloExtrato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloExtrato.setText("Extrato");

        javax.swing.GroupLayout jpExtratoLayout = new javax.swing.GroupLayout(jpExtrato);
        jpExtrato.setLayout(jpExtratoLayout);
        jpExtratoLayout.setHorizontalGroup(
            jpExtratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpExtratoLayout.createSequentialGroup()
                .addComponent(lblTituloExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jpExtratoLayout.setVerticalGroup(
            jpExtratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpExtratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloExtrato)
                .addContainerGap(442, Short.MAX_VALUE))
        );

        jpScrollExtrato.setViewportView(jpExtrato);

        jpAbas.addTab("Extrato", jpScrollExtrato);

        jpDepSaque.setBackground(new java.awt.Color(255, 255, 255));
        jpDepSaque.setPreferredSize(new java.awt.Dimension(840, 480));

        lblTituloSaque.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblTituloSaque.setForeground(new java.awt.Color(0, 153, 204));
        lblTituloSaque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSaque.setText("Saque");

        lblTituloDeposito.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblTituloDeposito.setForeground(new java.awt.Color(0, 153, 204));
        lblTituloDeposito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloDeposito.setText("Deposito");

        jpDeposito.setBackground(new java.awt.Color(255, 255, 255));
        jpDeposito.setMaximumSize(new java.awt.Dimension(840, 60));
        jpDeposito.setPreferredSize(new java.awt.Dimension(840, 60));

        lblValorDeposito.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        lblValorDeposito.setForeground(new java.awt.Color(0, 0, 0));
        lblValorDeposito.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorDeposito.setText("Valor de depósito:");
        lblValorDeposito.setPreferredSize(new java.awt.Dimension(160, 24));
        jpDeposito.add(lblValorDeposito);

        lblSeparador1.setFont(lblSaqueDepSenha.getFont());
        lblSeparador1.setForeground(new java.awt.Color(0, 0, 0));
        lblSeparador1.setText("R$");
        jpDeposito.add(lblSeparador1);

        saqueDepValorDeposito.setBackground(new java.awt.Color(204, 204, 255));
        saqueDepValorDeposito.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        saqueDepValorDeposito.setForeground(new java.awt.Color(0, 0, 0));
        saqueDepValorDeposito.setPreferredSize(new java.awt.Dimension(250, 30));
        jpDeposito.add(saqueDepValorDeposito);

        jpSaque.setBackground(new java.awt.Color(255, 255, 255));
        jpSaque.setMaximumSize(new java.awt.Dimension(840, 60));
        jpSaque.setPreferredSize(new java.awt.Dimension(840, 60));

        lblValorSaque.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        lblValorSaque.setForeground(new java.awt.Color(0, 0, 0));
        lblValorSaque.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorSaque.setText("Valor de saque:");
        lblValorSaque.setPreferredSize(new java.awt.Dimension(160, 24));
        jpSaque.add(lblValorSaque);

        lblSeparador2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        lblSeparador2.setForeground(new java.awt.Color(0, 0, 0));
        lblSeparador2.setText("R$");
        jpSaque.add(lblSeparador2);

        saqueDepValorSaque.setBackground(new java.awt.Color(204, 204, 255));
        saqueDepValorSaque.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 24)); // NOI18N
        saqueDepValorSaque.setForeground(new java.awt.Color(0, 0, 0));
        saqueDepValorSaque.setPreferredSize(new java.awt.Dimension(250, 30));
        jpSaque.add(saqueDepValorSaque);

        jpSaqueDepBotoes.setBackground(new java.awt.Color(255, 255, 255));

        saqueDepBtDepositar.setBackground(new java.awt.Color(0, 153, 204));
        saqueDepBtDepositar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        saqueDepBtDepositar.setForeground(new java.awt.Color(255, 255, 255));
        saqueDepBtDepositar.setText("Depositar");
        saqueDepBtDepositar.setFocusable(false);
        saqueDepBtDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueDepBtDepositarActionPerformed(evt);
            }
        });
        jpSaqueDepBotoes.add(saqueDepBtDepositar);

        saqueDepBtViewSaldo.setBackground(new java.awt.Color(0, 153, 204));
        saqueDepBtViewSaldo.setForeground(new java.awt.Color(255, 255, 255));
        saqueDepBtViewSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/olho-25x25.png"))); // NOI18N
        saqueDepBtViewSaldo.setFocusable(false);
        saqueDepBtViewSaldo.setMaximumSize(new java.awt.Dimension(50, 26));
        saqueDepBtViewSaldo.setMinimumSize(new java.awt.Dimension(50, 26));
        saqueDepBtViewSaldo.setPreferredSize(new java.awt.Dimension(50, 26));
        saqueDepBtViewSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueDepBtViewSaldoActionPerformed(evt);
            }
        });
        jpSaqueDepBotoes.add(saqueDepBtViewSaldo);

        saqueDepBtSacar.setBackground(new java.awt.Color(0, 153, 204));
        saqueDepBtSacar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        saqueDepBtSacar.setForeground(new java.awt.Color(255, 255, 255));
        saqueDepBtSacar.setText("Sacar");
        saqueDepBtSacar.setFocusable(false);
        saqueDepBtSacar.setMaximumSize(new java.awt.Dimension(100, 26));
        saqueDepBtSacar.setMinimumSize(new java.awt.Dimension(100, 26));
        saqueDepBtSacar.setPreferredSize(new java.awt.Dimension(100, 26));
        saqueDepBtSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueDepBtSacarActionPerformed(evt);
            }
        });
        jpSaqueDepBotoes.add(saqueDepBtSacar);

        jpSaqueDepSaldoAtual.setBackground(new java.awt.Color(255, 255, 255));
        jpSaqueDepSaldoAtual.setLayout(new java.awt.GridLayout(1, 2));

        lblSaqueDepSaldo.setFont(saldoBitcoinValor.getFont());
        lblSaqueDepSaldo.setForeground(new java.awt.Color(0, 0, 0));
        lblSaqueDepSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaqueDepSaldo.setText("Saldo em Reais:");
        lblSaqueDepSaldo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 30));
        jpSaqueDepSaldoAtual.add(lblSaqueDepSaldo);

        saqueDepSaldo.setFont(saldoBitcoinValor.getFont());
        saqueDepSaldo.setForeground(new java.awt.Color(0, 0, 0));
        saqueDepSaldo.setText("R$ -,--");
        saqueDepSaldo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 30));
        jpSaqueDepSaldoAtual.add(saqueDepSaldo);

        jpSaqDepSenha.setBackground(new java.awt.Color(255, 255, 255));
        jpSaqDepSenha.setMaximumSize(new java.awt.Dimension(840, 60));
        jpSaqDepSenha.setPreferredSize(new java.awt.Dimension(840, 60));

        lblSaqueDepSenha.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        lblSaqueDepSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblSaqueDepSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaqueDepSenha.setText("Senha");
        jpSaqDepSenha.add(lblSaqueDepSenha);

        saqueDepSenha.setBackground(new java.awt.Color(204, 204, 255));
        saqueDepSenha.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        saqueDepSenha.setForeground(new java.awt.Color(0, 0, 0));
        saqueDepSenha.setPreferredSize(new java.awt.Dimension(200, 30));
        jpSaqDepSenha.add(saqueDepSenha);

        saqueDepBtViewSenha.setBackground(new java.awt.Color(255, 246, 255));
        saqueDepBtViewSenha.setForeground(new java.awt.Color(255, 255, 255));
        saqueDepBtViewSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/olho-25x25.png"))); // NOI18N
        saqueDepBtViewSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        saqueDepBtViewSenha.setFocusable(false);
        saqueDepBtViewSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueDepBtViewSenhaActionPerformed(evt);
            }
        });
        jpSaqDepSenha.add(saqueDepBtViewSenha);

        javax.swing.GroupLayout jpDepSaqueLayout = new javax.swing.GroupLayout(jpDepSaque);
        jpDepSaque.setLayout(jpDepSaqueLayout);
        jpDepSaqueLayout.setHorizontalGroup(
            jpDepSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTituloSaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTituloDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpSaqueDepBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpSaqueDepSaldoAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpSaqDepSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpSaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpDepSaqueLayout.setVerticalGroup(
            jpDepSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDepSaqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloDeposito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTituloSaque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpSaqDepSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpSaqueDepSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jpSaqueDepBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jpAbas.addTab("Depósito / Saque", jpDepSaque);

        javax.swing.GroupLayout jpCompraLayout = new javax.swing.GroupLayout(jpCompra);
        jpCompra.setLayout(jpCompraLayout);
        jpCompraLayout.setHorizontalGroup(
            jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jpCompraLayout.setVerticalGroup(
            jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jpAbas.addTab("Compra", jpCompra);

        javax.swing.GroupLayout jpVendaLayout = new javax.swing.GroupLayout(jpVenda);
        jpVenda.setLayout(jpVendaLayout);
        jpVendaLayout.setHorizontalGroup(
            jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jpVendaLayout.setVerticalGroup(
            jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jpAbas.addTab("Venda", jpVenda);

        javax.swing.GroupLayout jpFundoLayout = new javax.swing.GroupLayout(jpFundo);
        jpFundo.setLayout(jpFundoLayout);
        jpFundoLayout.setHorizontalGroup(
            jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        jpFundoLayout.setVerticalGroup(
            jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFundoLayout.createSequentialGroup()
                .addComponent(jpAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saldoBtVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoBtVisualizarActionPerformed
        saldoVisivel = !saldoVisivel;
        saldoVisivel = c.saldoVisualizar(saldoVisivel);
    }//GEN-LAST:event_saldoBtVisualizarActionPerformed

    private void saldoBtAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoBtAtualizarActionPerformed
        c.saldoAtualizar(saldoVisivel);
    }//GEN-LAST:event_saldoBtAtualizarActionPerformed

    private void jpAbasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jpAbasStateChanged
        saldoVisivel = false;
        saqueSaldoVisivel = false;
        if(janelaIniciada){
            c.resetVisualizacoes();
        }
    }//GEN-LAST:event_jpAbasStateChanged

    private void saqueDepBtViewSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueDepBtViewSaldoActionPerformed
        saqueSaldoVisivel = !saqueSaldoVisivel;
        saqueSaldoVisivel = c.viewSaldoSaqueDeposito(saqueSaldoVisivel);
    }//GEN-LAST:event_saqueDepBtViewSaldoActionPerformed

    private void saqueDepBtDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueDepBtDepositarActionPerformed
        c.depositar();
    }//GEN-LAST:event_saqueDepBtDepositarActionPerformed

    private void saqueDepBtSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueDepBtSacarActionPerformed
        c.sacar();
    }//GEN-LAST:event_saqueDepBtSacarActionPerformed

    private void saqueDepBtViewSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueDepBtViewSenhaActionPerformed
        saqueSenhaVisivel = !saqueSenhaVisivel;
        c.viewSaqueSenha(saqueSenhaVisivel);
    }//GEN-LAST:event_saqueDepBtViewSenhaActionPerformed

    public JLabel getLblBemVindo() {
        return lblBemVindo;
    }
    public JLabel getLblSaldoCPF() {
        return lblSaldoCPF;
    }
    
    // Gets Aba Saldo
    public JLabel getSaldoBitcoinQtd() {
        return saldoBitcoinQtd;
    }
    public JLabel getSaldoBitcoinValor() {
        return saldoBitcoinValor;
    }
    public JButton getSaldoBtAtualizar() {
        return saldoBtAtualizar;
    }
    public JToggleButton getSaldoBtVisualizar() {
        return saldoBtVisualizar;
    }
    public JLabel getSaldoEtheriumQtd() {
        return saldoEtheriumQtd;
    }
    public JLabel getSaldoEtheriumValor() {
        return saldoEtheriumValor;
    }
    public JLabel getSaldoRealValor() {
        return saldoRealValor;
    }
    public JLabel getSaldoRippleQtd() {
        return saldoRippleQtd;
    }
    public JLabel getSaldoRippleValor() {
        return saldoRippleValor;
    }
    public JLabel getSaldoTotalValor() {
        return saldoTotalValor;
    }
    public boolean isSaldoVisivel() {
        return saldoVisivel;
    }

    // Aba Saque Deposito
    public JLabel getSaqueDepSaldo() {
        return saqueDepSaldo;
    }
    public JPasswordField getSaqueDepSenha() {
        return saqueDepSenha;
    }
    public JTextField getSaqueDepValorDeposito() {
        return saqueDepValorDeposito;
    }
    public JTextField getSaqueDepValorSaque() {
        return saqueDepValorSaque;
    }
    public JToggleButton getSaqueDepBtViewSaldo() {
        return saqueDepBtViewSaldo;
    }
    public boolean isSaqueSaldoVisivel() {
        return saqueSaldoVisivel;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JTabbedPane jpAbas;
    private javax.swing.JPanel jpCompra;
    private javax.swing.JPanel jpDepSaque;
    private javax.swing.JPanel jpDeposito;
    private javax.swing.JPanel jpExtrato;
    private javax.swing.JPanel jpFundo;
    private javax.swing.JPanel jpSaldo;
    private javax.swing.JPanel jpSaldoBotoes;
    private javax.swing.JPanel jpSaldoCriptos;
    private javax.swing.JPanel jpSaldoReal;
    private javax.swing.JPanel jpSaqDepSenha;
    private javax.swing.JPanel jpSaque;
    private javax.swing.JPanel jpSaqueDepBotoes;
    private javax.swing.JPanel jpSaqueDepSaldoAtual;
    private javax.swing.JScrollPane jpScrollExtrato;
    private javax.swing.JPanel jpValoresSaldo;
    private javax.swing.JPanel jpVenda;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblSaldoBitcoin;
    private javax.swing.JLabel lblSaldoCPF;
    private javax.swing.JLabel lblSaldoEtherium;
    private javax.swing.JLabel lblSaldoReal;
    private javax.swing.JLabel lblSaldoRipple;
    private javax.swing.JLabel lblSaldoTotal;
    private javax.swing.JLabel lblSaqueDepSaldo;
    private javax.swing.JLabel lblSaqueDepSenha;
    private javax.swing.JLabel lblSeparador1;
    private javax.swing.JLabel lblSeparador2;
    private javax.swing.JLabel lblTituloDeposito;
    private javax.swing.JLabel lblTituloExtrato;
    private javax.swing.JLabel lblTituloSaldo;
    private javax.swing.JLabel lblTituloSaque;
    private javax.swing.JLabel lblValorDeposito;
    private javax.swing.JLabel lblValorSaque;
    private javax.swing.JLabel saldoBitcoinQtd;
    private javax.swing.JLabel saldoBitcoinValor;
    private javax.swing.JButton saldoBtAtualizar;
    private javax.swing.JToggleButton saldoBtVisualizar;
    private javax.swing.JLabel saldoEtheriumQtd;
    private javax.swing.JLabel saldoEtheriumValor;
    private javax.swing.JLabel saldoRealValor;
    private javax.swing.JLabel saldoRippleQtd;
    private javax.swing.JLabel saldoRippleValor;
    private javax.swing.JLabel saldoTotalValor;
    private javax.swing.JButton saqueDepBtDepositar;
    private javax.swing.JButton saqueDepBtSacar;
    private javax.swing.JToggleButton saqueDepBtViewSaldo;
    private javax.swing.JToggleButton saqueDepBtViewSenha;
    private javax.swing.JLabel saqueDepSaldo;
    private javax.swing.JPasswordField saqueDepSenha;
    private javax.swing.JTextField saqueDepValorDeposito;
    private javax.swing.JTextField saqueDepValorSaque;
    // End of variables declaration//GEN-END:variables
}
